{
  "name": "SemanticModel",
  "compatibilityLevel": 1600,
  "model": {
    "culture": "en-US",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/GDG-ASGHARI-NB;WWIDW",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "GDG-ASGHARI-NB",
            "database": "WWIDW"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "Windows",
          "kind": "SQL",
          "path": "gdg-asghari-nb;WWIDW",
          "Username": "GI\\si.asghari",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "FactPurchaseOrders",
        "columns": [
          {
            "name": "PurchaseOrderKey",
            "dataType": "int64",
            "sourceColumn": "PurchaseOrderKey"
          },
          {
            "name": "PurchaseOrderAlternateKey",
            "dataType": "int64",
            "sourceColumn": "PurchaseOrderAlternateKey"
          },
          {
            "name": "PurchaseOrderLineAlternateKey",
            "dataType": "int64",
            "sourceColumn": "PurchaseOrderLineAlternateKey"
          },
          {
            "name": "SupplierKey",
            "dataType": "int64",
            "sourceColumn": "SupplierKey"
          },
          {
            "name": "OrderDateKey",
            "dataType": "int64",
            "sourceColumn": "OrderDateKey"
          },
          {
            "name": "ContactPersonKey",
            "dataType": "int64",
            "sourceColumn": "ContactPersonKey"
          },
          {
            "name": "ExpectedDeliveryDateKey",
            "dataType": "int64",
            "sourceColumn": "ExpectedDeliveryDateKey"
          },
          {
            "name": "IsOrderFinalized",
            "dataType": "boolean",
            "sourceColumn": "IsOrderFinalized"
          },
          {
            "name": "ItemKey",
            "dataType": "int64",
            "sourceColumn": "ItemKey"
          },
          {
            "name": "OrderedOuters",
            "dataType": "int64",
            "sourceColumn": "OrderedOuters"
          },
          {
            "name": "ReceivedOuters",
            "dataType": "int64",
            "sourceColumn": "ReceivedOuters"
          },
          {
            "name": "ExpectedUnitPricePerOuter",
            "dataType": "double",
            "sourceColumn": "ExpectedUnitPricePerOuter"
          },
          {
            "name": "LastReceiptDateKey",
            "dataType": "int64",
            "sourceColumn": "LastReceiptDateKey"
          },
          {
            "name": "IsOrderLineFinalized",
            "dataType": "boolean",
            "sourceColumn": "IsOrderLineFinalized"
          },
          {
            "type": "calculated",
            "name": "OrderItemAmount",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": " FactPurchaseOrders[ReceivedOuters] * FactPurchaseOrders[ExpectedUnitPricePerOuter]"
          }
        ],
        "partitions": [
          {
            "name": "PurchaseOrders2013",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/GDG-ASGHARI-NB;WWIDW\",",
                "    dbo_FactPurchaseOrders = Source{[Schema=\"dbo\",Item=\"FactPurchaseOrders\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_FactPurchaseOrders, each [OrderDateKey] >= 20130101 and [OrderDateKey] < 20140101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/GDG-ASGHARI-NB;WWIDW\",",
                  "    dbo_FactPurchaseOrders = Source{[Schema=\"dbo\",Item=\"FactPurchaseOrders\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_FactPurchaseOrders, each [OrderDateKey] >= 20130101 and [OrderDateKey] < 20140101)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "PurchaseOrders2014",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/GDG-ASGHARI-NB;WWIDW\",",
                "    dbo_FactPurchaseOrders = Source{[Schema=\"dbo\",Item=\"FactPurchaseOrders\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_FactPurchaseOrders, each [OrderDateKey] >= 20140101 and [OrderDateKey] < 20150101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/GDG-ASGHARI-NB;WWIDW\",",
                  "    dbo_FactPurchaseOrders = Source{[Schema=\"dbo\",Item=\"FactPurchaseOrders\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_FactPurchaseOrders, each [OrderDateKey] >= 20140101 and [OrderDateKey] < 20150101)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "PurchaseOrders2015",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/GDG-ASGHARI-NB;WWIDW\",",
                "    dbo_FactPurchaseOrders = Source{[Schema=\"dbo\",Item=\"FactPurchaseOrders\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_FactPurchaseOrders, each [OrderDateKey] >= 20150101 and [OrderDateKey] < 20160101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/GDG-ASGHARI-NB;WWIDW\",",
                  "    dbo_FactPurchaseOrders = Source{[Schema=\"dbo\",Item=\"FactPurchaseOrders\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_FactPurchaseOrders, each [OrderDateKey] >= 20150101 and [OrderDateKey] < 20160101)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "PurchaseOrders2016andAfter",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/GDG-ASGHARI-NB;WWIDW\",",
                "    dbo_FactPurchaseOrders = Source{[Schema=\"dbo\",Item=\"FactPurchaseOrders\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_FactPurchaseOrders, each [OrderDateKey] >= 20160101 and [OrderDateKey] < 20500101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/GDG-ASGHARI-NB;WWIDW\",",
                  "    dbo_FactPurchaseOrders = Source{[Schema=\"dbo\",Item=\"FactPurchaseOrders\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_FactPurchaseOrders, each [OrderDateKey] >= 20160101 and [OrderDateKey] < 20500101)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ]
      },
      {
        "name": "DimDate",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "Date"
          },
          {
            "name": "FullDate",
            "dataType": "string",
            "sourceColumn": "FullDate"
          },
          {
            "name": "DayOfMonth",
            "dataType": "string",
            "sourceColumn": "DayOfMonth"
          },
          {
            "name": "DaySuffix",
            "dataType": "string",
            "sourceColumn": "DaySuffix"
          },
          {
            "name": "DayName",
            "dataType": "string",
            "sourceColumn": "DayName"
          },
          {
            "name": "DayOfWeek",
            "dataType": "string",
            "sourceColumn": "DayOfWeek"
          },
          {
            "name": "DayOfWeekInMonth",
            "dataType": "string",
            "sourceColumn": "DayOfWeekInMonth"
          },
          {
            "name": "DayOfWeekInYear",
            "dataType": "string",
            "sourceColumn": "DayOfWeekInYear"
          },
          {
            "name": "DayOfQuarter",
            "dataType": "string",
            "sourceColumn": "DayOfQuarter"
          },
          {
            "name": "DayOfYear",
            "dataType": "string",
            "sourceColumn": "DayOfYear"
          },
          {
            "name": "WeekOfMonth",
            "dataType": "string",
            "sourceColumn": "WeekOfMonth"
          },
          {
            "name": "WeekOfQuarter",
            "dataType": "string",
            "sourceColumn": "WeekOfQuarter"
          },
          {
            "name": "WeekOfYear",
            "dataType": "string",
            "sourceColumn": "WeekOfYear"
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month"
          },
          {
            "name": "MonthName",
            "dataType": "string",
            "sourceColumn": "MonthName"
          },
          {
            "name": "MonthOfQuarter",
            "dataType": "string",
            "sourceColumn": "MonthOfQuarter"
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter"
          },
          {
            "name": "QuarterName",
            "dataType": "string",
            "sourceColumn": "QuarterName"
          },
          {
            "name": "Year",
            "dataType": "string",
            "sourceColumn": "Year"
          },
          {
            "name": "YearName",
            "dataType": "string",
            "sourceColumn": "YearName"
          },
          {
            "name": "MonthYear",
            "dataType": "string",
            "sourceColumn": "MonthYear"
          },
          {
            "name": "MMYYYY",
            "dataType": "string",
            "sourceColumn": "MMYYYY"
          },
          {
            "name": "FirstDayOfMonth",
            "dataType": "dateTime",
            "sourceColumn": "FirstDayOfMonth"
          },
          {
            "name": "LastDayOfMonth",
            "dataType": "dateTime",
            "sourceColumn": "LastDayOfMonth"
          },
          {
            "name": "FirstDayOfQuarter",
            "dataType": "dateTime",
            "sourceColumn": "FirstDayOfQuarter"
          },
          {
            "name": "LastDayOfQuarter",
            "dataType": "dateTime",
            "sourceColumn": "LastDayOfQuarter"
          },
          {
            "name": "FirstDayOfYear",
            "dataType": "dateTime",
            "sourceColumn": "FirstDayOfYear"
          },
          {
            "name": "LastDayOfYear",
            "dataType": "dateTime",
            "sourceColumn": "LastDayOfYear"
          },
          {
            "name": "IsHoliday",
            "dataType": "boolean",
            "sourceColumn": "IsHoliday"
          },
          {
            "name": "IsWeekday",
            "dataType": "boolean",
            "sourceColumn": "IsWeekday"
          },
          {
            "name": "HolidayName",
            "dataType": "string",
            "sourceColumn": "HolidayName"
          },
          {
            "name": "FiscalDayOfYear",
            "dataType": "string",
            "sourceColumn": "FiscalDayOfYear"
          },
          {
            "name": "FiscalWeekOfYear",
            "dataType": "string",
            "sourceColumn": "FiscalWeekOfYear"
          },
          {
            "name": "FiscalMonth",
            "dataType": "string",
            "sourceColumn": "FiscalMonth"
          },
          {
            "name": "FiscalQuarter",
            "dataType": "string",
            "sourceColumn": "FiscalQuarter"
          },
          {
            "name": "FiscalQuarterName",
            "dataType": "string",
            "sourceColumn": "FiscalQuarterName"
          },
          {
            "name": "FiscalYear",
            "dataType": "string",
            "sourceColumn": "FiscalYear"
          },
          {
            "name": "FiscalYearName",
            "dataType": "string",
            "sourceColumn": "FiscalYearName"
          },
          {
            "name": "FiscalMonthYear",
            "dataType": "string",
            "sourceColumn": "FiscalMonthYear"
          },
          {
            "name": "FiscalMMYYYY",
            "dataType": "string",
            "sourceColumn": "FiscalMMYYYY"
          },
          {
            "name": "FiscalFirstDayOfMonth",
            "dataType": "dateTime",
            "sourceColumn": "FiscalFirstDayOfMonth"
          },
          {
            "name": "FiscalLastDayOfMonth",
            "dataType": "dateTime",
            "sourceColumn": "FiscalLastDayOfMonth"
          },
          {
            "name": "FiscalFirstDayOfQuarter",
            "dataType": "dateTime",
            "sourceColumn": "FiscalFirstDayOfQuarter"
          },
          {
            "name": "FiscalLastDayOfQuarter",
            "dataType": "dateTime",
            "sourceColumn": "FiscalLastDayOfQuarter"
          },
          {
            "name": "FiscalFirstDayOfYear",
            "dataType": "dateTime",
            "sourceColumn": "FiscalFirstDayOfYear"
          },
          {
            "name": "FiscalLastDayOfYear",
            "dataType": "dateTime",
            "sourceColumn": "FiscalLastDayOfYear"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/GDG-ASGHARI-NB;WWIDW\",",
                "    dbo_DimDate = Source{[Schema=\"dbo\",Item=\"DimDate\"]}[Data]",
                "in",
                "    dbo_DimDate"
              ]
            }
          }
        ]
      },
      {
        "name": "DimItems",
        "columns": [
          {
            "name": "ItemKey",
            "dataType": "int64",
            "sourceColumn": "ItemKey"
          },
          {
            "name": "ItemAlternateKey",
            "dataType": "int64",
            "sourceColumn": "ItemAlternateKey"
          },
          {
            "name": "ItemName",
            "dataType": "string",
            "sourceColumn": "ItemName"
          },
          {
            "name": "SupplierKey",
            "dataType": "int64",
            "sourceColumn": "SupplierKey"
          },
          {
            "name": "Color",
            "dataType": "string",
            "sourceColumn": "Color"
          },
          {
            "name": "UnitPackage",
            "dataType": "string",
            "sourceColumn": "UnitPackage"
          },
          {
            "name": "OuterPackage",
            "dataType": "string",
            "sourceColumn": "OuterPackage"
          },
          {
            "name": "Brand",
            "dataType": "string",
            "sourceColumn": "Brand"
          },
          {
            "name": "Size",
            "dataType": "string",
            "sourceColumn": "Size"
          },
          {
            "name": "QuantityOnHand",
            "dataType": "int64",
            "sourceColumn": "QuantityOnHand"
          },
          {
            "name": "BinLocation",
            "dataType": "string",
            "sourceColumn": "BinLocation"
          },
          {
            "name": "LastStocktakeQuantity",
            "dataType": "int64",
            "sourceColumn": "LastStocktakeQuantity"
          },
          {
            "name": "LastCostPrice",
            "dataType": "double",
            "sourceColumn": "LastCostPrice"
          },
          {
            "name": "ReorderLevel",
            "dataType": "int64",
            "sourceColumn": "ReorderLevel"
          },
          {
            "name": "TargetStockLevel",
            "dataType": "int64",
            "sourceColumn": "TargetStockLevel"
          },
          {
            "name": "LeadTimeDays",
            "dataType": "int64",
            "sourceColumn": "LeadTimeDays"
          },
          {
            "name": "QuantityPerOuter",
            "dataType": "int64",
            "sourceColumn": "QuantityPerOuter"
          },
          {
            "name": "IsChillerStock",
            "dataType": "boolean",
            "sourceColumn": "IsChillerStock"
          },
          {
            "name": "Barcode",
            "dataType": "string",
            "sourceColumn": "Barcode"
          },
          {
            "name": "TaxRate",
            "dataType": "double",
            "sourceColumn": "TaxRate"
          },
          {
            "name": "UnitPrice",
            "dataType": "double",
            "sourceColumn": "UnitPrice"
          },
          {
            "name": "RecommendedRetailPrice",
            "dataType": "double",
            "sourceColumn": "RecommendedRetailPrice"
          },
          {
            "name": "TypicalWeightPerUnit",
            "dataType": "double",
            "sourceColumn": "TypicalWeightPerUnit"
          },
          {
            "name": "MarketingComments",
            "dataType": "string",
            "sourceColumn": "MarketingComments"
          },
          {
            "name": "InternalComments",
            "dataType": "string",
            "sourceColumn": "InternalComments"
          },
          {
            "name": "CountryOfManufacture",
            "dataType": "string",
            "sourceColumn": "CountryOfManufacture"
          },
          {
            "name": "SearchDetails",
            "dataType": "string",
            "sourceColumn": "SearchDetails"
          },
          {
            "name": "StartDate",
            "dataType": "dateTime",
            "sourceColumn": "StartDate"
          },
          {
            "name": "EndDate",
            "dataType": "dateTime",
            "sourceColumn": "EndDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/GDG-ASGHARI-NB;WWIDW\",",
                "    dbo_DimItems = Source{[Schema=\"dbo\",Item=\"DimItems\"]}[Data]",
                "in",
                "    dbo_DimItems"
              ]
            }
          }
        ]
      },
      {
        "name": "DimSuppliers",
        "columns": [
          {
            "name": "SupplierKey",
            "dataType": "int64",
            "sourceColumn": "SupplierKey"
          },
          {
            "name": "SupplierAlternateKey",
            "dataType": "int64",
            "sourceColumn": "SupplierAlternateKey"
          },
          {
            "name": "SupplierName",
            "dataType": "string",
            "sourceColumn": "SupplierName"
          },
          {
            "name": "SupplierCategory",
            "dataType": "string",
            "sourceColumn": "SupplierCategory"
          },
          {
            "name": "PrimaryContactPersonKey",
            "dataType": "int64",
            "sourceColumn": "PrimaryContactPersonKey"
          },
          {
            "name": "AlternateContactPersonKey",
            "dataType": "int64",
            "sourceColumn": "AlternateContactPersonKey"
          },
          {
            "name": "GeoKey",
            "dataType": "int64",
            "sourceColumn": "GeoKey"
          },
          {
            "name": "DeliveryMethodKey",
            "dataType": "int64",
            "sourceColumn": "DeliveryMethodKey"
          },
          {
            "name": "SupplierReference",
            "dataType": "string",
            "sourceColumn": "SupplierReference"
          },
          {
            "name": "BankAccountName",
            "dataType": "string",
            "sourceColumn": "BankAccountName"
          },
          {
            "name": "BankAccountBranch",
            "dataType": "string",
            "sourceColumn": "BankAccountBranch"
          },
          {
            "name": "BankAccountCode",
            "dataType": "string",
            "sourceColumn": "BankAccountCode"
          },
          {
            "name": "BankAccountNumber",
            "dataType": "string",
            "sourceColumn": "BankAccountNumber"
          },
          {
            "name": "BankInternationalCode",
            "dataType": "string",
            "sourceColumn": "BankInternationalCode"
          },
          {
            "name": "PaymentDays",
            "dataType": "int64",
            "sourceColumn": "PaymentDays"
          },
          {
            "name": "InternalComments",
            "dataType": "string",
            "sourceColumn": "InternalComments"
          },
          {
            "name": "PhoneNumber",
            "dataType": "string",
            "sourceColumn": "PhoneNumber"
          },
          {
            "name": "FaxNumber",
            "dataType": "string",
            "sourceColumn": "FaxNumber"
          },
          {
            "name": "WebsiteURL",
            "dataType": "string",
            "sourceColumn": "WebsiteURL"
          },
          {
            "name": "StartDate",
            "dataType": "dateTime",
            "sourceColumn": "StartDate"
          },
          {
            "name": "EndDate",
            "dataType": "dateTime",
            "sourceColumn": "EndDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/GDG-ASGHARI-NB;WWIDW\",",
                "    dbo_DimSuppliers = Source{[Schema=\"dbo\",Item=\"DimSuppliers\"]}[Data]",
                "in",
                "    dbo_DimSuppliers"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "SupplierCategoryNameHierarchy",
            "levels": [
              {
                "name": "SupplierCategory",
                "ordinal": 0,
                "column": "SupplierCategory"
              },
              {
                "name": "SupplierName",
                "ordinal": 1,
                "column": "SupplierName"
              }
            ]
          }
        ]
      },
      {
        "name": "DimPerson",
        "columns": [
          {
            "name": "PersonKey",
            "dataType": "int64",
            "sourceColumn": "PersonKey"
          },
          {
            "name": "PersonParentKey",
            "dataType": "int64",
            "sourceColumn": "PersonParentKey"
          },
          {
            "name": "PersonAlternateKey",
            "dataType": "int64",
            "sourceColumn": "PersonAlternateKey"
          },
          {
            "name": "PersonParentAlternateKey",
            "dataType": "int64",
            "sourceColumn": "PersonParentAlternateKey"
          },
          {
            "name": "FullName",
            "dataType": "string",
            "sourceColumn": "FullName"
          },
          {
            "name": "PreferredName",
            "dataType": "string",
            "sourceColumn": "PreferredName"
          },
          {
            "name": "SearchName",
            "dataType": "string",
            "sourceColumn": "SearchName"
          },
          {
            "name": "IsPermittedToLogon",
            "dataType": "boolean",
            "sourceColumn": "IsPermittedToLogon"
          },
          {
            "name": "LogonName",
            "dataType": "string",
            "sourceColumn": "LogonName"
          },
          {
            "name": "IsExternalLogonProvider",
            "dataType": "boolean",
            "sourceColumn": "IsExternalLogonProvider"
          },
          {
            "name": "IsSystemUser",
            "dataType": "boolean",
            "sourceColumn": "IsSystemUser"
          },
          {
            "name": "IsEmployee",
            "dataType": "boolean",
            "sourceColumn": "IsEmployee"
          },
          {
            "name": "EmployeePosition",
            "dataType": "string",
            "sourceColumn": "EmployeePosition"
          },
          {
            "name": "IsSalesperson",
            "dataType": "boolean",
            "sourceColumn": "IsSalesperson"
          },
          {
            "name": "PhoneNumber",
            "dataType": "string",
            "sourceColumn": "PhoneNumber"
          },
          {
            "name": "FaxNumber",
            "dataType": "string",
            "sourceColumn": "FaxNumber"
          },
          {
            "name": "EmailAddress",
            "dataType": "string",
            "sourceColumn": "EmailAddress"
          },
          {
            "name": "StartDate",
            "dataType": "dateTime",
            "sourceColumn": "StartDate"
          },
          {
            "name": "EndDate",
            "dataType": "dateTime",
            "sourceColumn": "EndDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/GDG-ASGHARI-NB;WWIDW\",",
                "    dbo_DimPerson = Source{[Schema=\"dbo\",Item=\"DimPerson\"]}[Data]",
                "in",
                "    dbo_DimPerson"
              ]
            }
          }
        ]
      },
      {
        "name": "_Measures",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Date]"
          },
          {
            "type": "calculated",
            "name": "Measure",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "Description",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "ReferenceTable",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": " SELECTCOLUMNS( CALENDAR( \"2025-01-01\", \"2025-01-01\" ), \"Date\", [Date] )"
            }
          }
        ],
        "measures": [
          {
            "name": "PO Average Unit Price",
            "expression": [
              "",
              "AVERAGE ( FactPurchaseOrders[ExpectedUnitPricePerOuter] )"
            ],
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0",
            "displayFolder": "Averages",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"1\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PO Total Order Amount",
            "expression": [
              "",
              "SUM ( FactPurchaseOrders[OrderItemAmount] )"
            ],
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0",
            "displayFolder": "Totals",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"1\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PO Total Item Recieved Quantity",
            "expression": [
              "",
              "SUM ( FactPurchaseOrders[ReceivedOuters] )"
            ],
            "formatString": "#,0",
            "displayFolder": "Totals"
          },
          {
            "name": "PO Total Item Ordered Quantity",
            "expression": [
              "",
              "SUM ( FactPurchaseOrders[OrderedOuters] )"
            ],
            "formatString": "#,0",
            "displayFolder": "Totals"
          },
          {
            "name": "Total PO",
            "expression": [
              "",
              "DISTINCTCOUNT ( FactPurchaseOrders[PurchaseOrderAlternateKey] )"
            ],
            "formatString": "#,0",
            "displayFolder": "Totals"
          },
          {
            "name": "Total PO Items",
            "expression": [
              "",
              "COUNTROWS ( FactPurchaseOrders )"
            ],
            "formatString": "#,0",
            "displayFolder": "Totals"
          },
          {
            "name": "Total Suppliers",
            "expression": [
              "",
              "COUNTROWS ( DimSuppliers )"
            ]
          },
          {
            "name": "Total Items",
            "expression": " COUNTROWS(DimItems)"
          },
          {
            "name": "Total Person",
            "expression": " COUNTROWS(DimPerson)"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "38834e50-b792-472f-9a79-f5890e39b3b5",
        "fromTable": "FactPurchaseOrders",
        "fromColumn": "ExpectedDeliveryDateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "dfd68cf1-0ecb-4f3d-b080-0ce62f0b7739",
        "fromTable": "FactPurchaseOrders",
        "fromColumn": "LastReceiptDateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "0f1f2172-7fa6-42ba-919b-38ed24b88a3a",
        "fromTable": "DimItems",
        "fromColumn": "SupplierKey",
        "toTable": "DimSuppliers",
        "toColumn": "SupplierKey",
        "isActive": false
      },
      {
        "name": "d3c7c42e-07a0-4f75-8a0c-f97d572b4efe",
        "fromTable": "FactPurchaseOrders",
        "fromColumn": "OrderDateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "06edf6fd-0ba8-4eb7-8715-c671e402cc8b",
        "fromTable": "FactPurchaseOrders",
        "fromColumn": "ItemKey",
        "toTable": "DimItems",
        "toColumn": "ItemKey"
      },
      {
        "name": "c5ec0963-6999-427d-bd72-ba67300bb8db",
        "fromTable": "FactPurchaseOrders",
        "fromColumn": "ContactPersonKey",
        "toTable": "DimPerson",
        "toColumn": "PersonKey"
      },
      {
        "name": "2473b830-ada8-4771-aeb8-10304dd1af20",
        "fromTable": "DimSuppliers",
        "fromColumn": "PrimaryContactPersonKey",
        "toTable": "DimPerson",
        "toColumn": "PersonKey",
        "isActive": false
      },
      {
        "name": "0718298a-4602-4cc1-8d51-df696a6e791a",
        "fromTable": "FactPurchaseOrders",
        "fromColumn": "SupplierKey",
        "toTable": "DimSuppliers",
        "toColumn": "SupplierKey"
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "700"
      }
    ]
  },
  "id": "SemanticModel"
}